### ISSUE TITLE
Binary_sensors are not updating

### ISSUE THREAD

**Issue by sindrebroch** [sindrebroch/ha-flexit#14]
## Version of the custom_component
2.1.5

## Describe the bug
The binary_sensors are not updating their value. Noticed when resetting the filter-alarm in the Flexit Go-app. 

Can be reproduced by watching the attributes of dirty_filter.

The sensors update on restart.

**Comment by uphillbattle** [comment]
I noticed the same yesterday and was going to report it here just now, but discovered that you had opened the issue yourself. 😄

**Comment by sindrebroch** [comment]
Should be fixed in [2.2.0](https://github.com/sindrebroch/ha-flexit/releases/tag/2.2.0)
