### ISSUE TITLE
Can't change to HOME mode

### ISSUE THREAD

**Issue by Soleg06** [sindrebroch/ha-flexit#19]
I have an S4 Flexit FTX and tested some of your code and it works fine!
I can change MODE to AWAY or FIREPLACE but the problem is I can't change it back to HOME.
I checked the code and the path used for this PUT is:
MODE_HOME_HIGH_CAL_PUT_PATH = ";1!01300002A000055" it seems to arrive OK and I get Success from the api but nothing happens with the MODE in the S¤.
Is it the wrong path? or is something else off?

**Comment by sindrebroch** [comment]
Are you using the API directly or the integration? Which mode are you in? 

The API can be a bit weird sometimes. For the new modes added recently, away with delay and fireplace need to be "toggled off" to exit the mode. If you specify a bit I can show where I handle it in code.

**Comment by sindrebroch** [comment]
Correct, set_preset_mode handles this. Not sure yet if it's 100% stable as this was recently released in the integration, but it has been working for me so far, and no issues reported.

I have been sniffing the traffic from the flexit go-app, and trying things from there. I used fiddler3 on windows and set it up as a proxy with https-decrypting to see the paths and values.

**Comment by Soleg06** [comment]
Thank you! I been testing and I think I found something that might be a little bug:

The reply to the question with the path MODE_HOME_HIGH_CAL_PUT_PATH contains mode and
the answer to the question with path MODE_PATH also contains mode.
But there is a difference that matters in the toggle modes that caused the logic to fail because I got the "wrong" mode back from the FTX.
The real actual mode the FTX are in are the answer to MODE_PATH question!
The mode from MODE_HOME_HIGH_CAL_PUT_PATH are sort of "pending mode" that is the mode the FTX will change to when the timer has expired or when I send the same command again (fireplace for fireplace).
I changed to MODE_PATH in SENSOR_DATA_PATH_LIST and now it works perfectly. Maybe consider changing it in your code as well?

I also have been sniffing traffic for other api:s but I used Postman that has a nice plugin for the browser or a proxy you can use.
But in the case with Flexit there are no PC based website and I have the app on an Iphone and I can't get a new certificate on it. At least I haven't found a way to, so I can't sniff the https traffic.
Glad you did!

**Comment by sindrebroch** [comment]
I think I had some issues with using the MODE_PATH for this, but I don't remember what it was specifically. Maybe I just didn't want to juggle both of them, as it seemed simpler to just use one. I'll look into it at some point. Thanks for the tip. 

Closing this, as it isn't really an issue with the integration. I opened the Discussions-tab, so if there are any more questions you can post them there.
