### ISSUE TITLE
HVAC Modes

### ISSUE THREAD

**Issue by vegargrim** [sindrebroch/ha-flexit#21]
Hello and thanks for a great plugin!

I was wondering if it is possible to get the home, away, boost and fireplace presets as HVAC modes. I am using home assistant for this plugin and toshiba AC control to integrate it with homekit. It would be really nice to set boost and fireplace with homekit. But for that to work, I have to figure out how to get these as modes.

As you can see on the picture, I can change between warm up, cool, auto and off on my air condition unit. But on the flexit plugin it only shows fan/heat on/off. Thats why I want fireplace and boost at the same way as the AC.

Do you know how I can do this, or is it something you need to change?

Sorry if im missing something obvious, but im really new to home assistant.

![736E5951-DA06-4797-B784-77AE96BF7EFF](https://user-images.githubusercontent.com/64918601/157489708-d785fb3e-0bd6-49b2-b5a7-4bb6b9d63aaf.jpeg)

**Comment by sindrebroch** [comment]
Hi. Thanks for the question. I have been thinking about it a bit, but personally I use schedules and automations so I haven't dove too deep into it.

As I understand it, adding these modes as hvac_modes goes against the design of the climate entity in HomeAssistant. 
See homeassistant developer doc on HVAC modes [here](https://developers.home-assistant.io/docs/core/entity/climate/#hvac-modes)
`You are only allowed to use the built-in HVAC modes. If you want another mode, add a preset instead.` 
I'm not sure about the reason for limiting hvac modes, but I don't want to implement something out of spec if I can help it. It is supposed to be a preset.

The workaround would be to create scripts, template-buttons, template-select or whatever works best for you, for setting the different presets, and use them as a separate tile / entity in Homekit. Maybe even grouping them would be possible? I'm not really very familiar with the details of Homekit.

**Comment by vegargrim** [comment]
Thanks for the quick reply! I will check out what you said about scripts etc. I see how homeassistant is limiting different names as modes.

**Comment by sindrebroch** [comment]
Great! Closing the issue, but feel free to ask more questions in issues or discussions.

**Comment by vegargrim** [comment]
Hi, I have one more question. Is it possible for you to add the preset modes as button entities?

Example: button.activate_Home
button.activate_Away
button.activate_Boost
button.activate_Boost Temporary
button.activate_Fireplace

Is this too much work?

**Comment by sindrebroch** [comment]
@vegargrim It would be possible, but I think adding single entities for all different single functions will make the integration rather messy and bloated. Having multiple entities in the integration doing the same thing seems like an anti-pattern, and previously I had some issues keeping them in sync / triggering updates at the same time.

You could tweak this yourself, just the way you would like. You could simply add scripts or [template-buttons](https://www.home-assistant.io/integrations/template/) calling the set_preset_mode-service. For instance:
```
service: climate.set_preset_mode
data:
  preset_mode: home
target:
  entity_id: climate.flexit
```

I can try assisting with this if it seems difficult, but I would need to know more about your homeassistant setup.

**Comment by vegargrim** [comment]
Okey, thanks for the input. I started looking at creating buttons, so I will dig deeper into that 👍🏼
