### ISSUE TITLE
Unsupported NumberEnity used, will be deprecated in Home Assistant 2022.10

### ISSUE THREAD

**Issue by Aviatorpaal** [sindrebroch/ha-flexit#25]
## Version of the custom_component

2.3.0

## Configuration

```yaml

No changes to the config file, integration installed using HACS

```

## Describe the bug

Thank you very much for creating a great integration - works great for all my needs! Bug: NumberEntity not supported by Home Assistant in future releases

## Debug log

Logger: homeassistant.components.number
Source: components/number/__init__.py:462 
Integration: Number (documentation, issues) 
First occurred: 10:36:07 (3 occurrences) 
Last logged: 10:36:07

Entity None (<class 'custom_components.flexit.number.FlexitAwayDelayNumber'>) is using deprecated NumberEntity features which will be unsupported from Home Assistant Core 2022.10, please report it to the custom component author.
Entity None (<class 'custom_components.flexit.number.FlexitBoostDurationNumber'>) is using deprecated NumberEntity features which will be unsupported from Home Assistant Core 2022.10, please report it to the custom component author.
Entity None (<class 'custom_components.flexit.number.FlexitFireplaceDurationNumber'>) is using deprecated NumberEntity features which will be unsupported from Home Assistant Core 2022.10, please report it to the custom component author.

Logger: homeassistant.components.number
Source: components/number/__init__.py:220 
Integration: Number (documentation, issues) 
First occurred: 10:36:07 (4 occurrences) 
Last logged: 10:36:07

custom_components.flexit.number::FlexitNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom component author.
custom_components.flexit.number::FlexitFireplaceDurationNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom component author.
custom_components.flexit.number::FlexitBoostDurationNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom component author.
custom_components.flexit.number::FlexitAwayDelayNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom component author.

Logger: homeassistant.components.number
Source: components/number/__init__.py:152 
Integration: Number (documentation, issues) 
First occurred: 10:36:07 (3 occurrences) 
Last logged: 10:36:07

custom_components.flexit.number is setting deprecated attributes on an instance of NumberEntityDescription, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom component author.

```text



```

**Comment by sindrebroch** [comment]
Thanks for reporting!

Should be fixed in release [2.3.1](https://github.com/sindrebroch/ha-flexit/releases/tag/2.3.1).

Please reopen if you continue to see this issue.
