### ISSUE TITLE
Starting configuration

### ISSUE THREAD

**Issue by jonte964** [sindrebroch/ha-flexit#3]
There could be an issue with how to configure or rather how to start the configuration. 

Running on a Pi installation and have done manual as well as HACS installation. 

In both cases I have not been able to find where to start the configuration. 

My S4 is connected over Ethernet and I have no new devices and no configuration button. 

Very likely I’m doing something wrong though.

**Comment by sindrebroch** [comment]
Hi. Have you tried adding it as an integration on the integration page? After installing through hacs, homeassistant needs a restart and then it should be available to setup from the integrations-page like any other component. 

Or is there an issue where nothing appears after the configuration? If so, are there any logs available? 

Thanks for reporting, looking to improve the integration.

**Comment by jonte964** [comment]
Hi, 
I believe the issue was on my side and I managed to resolve it with your above guidance. Thanks!

Looking forward to the guide on getting the subscription key!

**Comment by sindrebroch** [comment]
@jonte964 In the newest version the subscription key is no longer required, so it should be easier to setup.
