### ISSUE TITLE
Temperature Room

### ISSUE THREAD

**Issue by sindrebroch** [sindrebroch/ha-flexit#31]
### Discussed in https://github.com/sindrebroch/ha-flexit/discussions/22

<div type='discussions-op-text'>

<sup>Originally posted by **feanor-anglin** March 22, 2022</sup>
Hi, I have a question about Temperature Room sensor. Do I need any additional hardware to see the value of this sensor? Right now I have it at 0 degrees.

Is this a different value than Temperature Extract? Why can't this two sensors be combined? </div>

**Comment by Aviatorpaal** [comment]
On my S3 I do get a sensible value from the "Temperature Room" sensor

**Comment by sindrebroch** [comment]
@Aviatorpaal Good! Do you know if the S3 is the same as "model POS3.67"?

**Comment by Aviatorpaal** [comment]
> @Aviatorpaal Good! Do you know if the S3 is the same as "model POS3.67"?

Yes - my Nordic S3(R - for orientation, I believe) is model POS.67 😃

**Comment by sindrebroch** [comment]
Great, thanks! I guess I'll just close this issue then. Not sure I liked the suggested solution either.

**Comment by jm-cook** [comment]
What was the fix for this? I have 0 degrees for the room sensor, and also 0 for current sensor with the climate entity, The model is given as POS3.6715/414. Flexit Nordic CL3.
