### ISSUE TITLE
Where is esphome-walkingpad repo?

### ISSUE THREAD

**Issue by MegaSegaDrive8** [sindrebroch/ha-flexit#34]
Hello. Sorry for that, but where is https://github.com/sindrebroch/esphome-walkingpad ? I really need this repository

**Comment by sindrebroch** [comment]
Hi. It's archived because it wasn't close to working, and I have not put any more work into it. I will open up the repo if there is some progress.

**Comment by MegaSegaDrive8** [comment]
Tthanx for answer. Maybe you can shared this repo for me and we can together publish this repo for all HA communtiy?

**Comment by sindrebroch** [comment]
I would if it was anywhere close to working, as it stands now, there is no functionality implemented. I also think the best effort forward would be to implement native HA-support now that bluetooth has become much better in HA. This would probably be easier to implement, as there already are implementations in python, like [this](https://github.com/ph4r05/ph4-walkingpad).
