### ISSUE TITLE
Deprecation of async_setup_platforms

### ISSUE THREAD

**Issue by alekso56** [sindrebroch/ha-flexit#35]
Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for flexit using this method at [custom_components/flexit/__init__.py](https://github.com/sindrebroch/ha-flexit/blob/202463c0ce7f63c6b54ae7a2f056e8826dbf30f7/custom_components/flexit/__init__.py#L50), line 50: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

**Comment by sindrebroch** [comment]
Thanks for reporting, will get right on it!

**Comment by sindrebroch** [comment]
Fixed in [2.3.3](https://github.com/sindrebroch/ha-flexit/releases/tag/2.3.3)
