### ISSUE TITLE
Flere sensorer - varmegjenvinner, viftehastighet

### ISSUE THREAD

**Issue by kazzkizz** [sindrebroch/ha-flexit#5]
Først og fremst; super integrasjon. Godt jobba! 👍 
Lekende lett å få inn i HA etter en restart av nettleser - det er nok en kjent sak ifbm. HACS, men lenge siden sist. :) 

* Ønsker gjerne se hastighet på vifter og varmegjenvinner. :-) 

Hos meg er Dirty Filter status Av, i Flexit app sier den ca 1 mnd igjen til bytte. Noe jeg har misset?

**Comment by sindrebroch** [comment]
Så bra integrasjonen funker bra! Gjenstart gjelder nok alle custom integrasjoner som legges til ja :)

Godt forslag om viftehastighet, det er notert, kan prøve å få lagt det til etterhvert! Verdiene vil jo ikke oppdateres sånn kjempeofte, men hvis det gir nytte kan vi slenge det på. 

Når det gjelder dirty_filter så skal den skru seg til «on» når filteret skal byttes. Timer brukt og «limit» ligger som attributter på dirty_filter, så de kan du bruke med en template sensor om du vil til å regne om til dager gjenstående eller hva enn :) Har ikke selv sett om sensoren funker i praksis, da jeg ikke har trengt å bytte filter ila denne perioden, men det er tenkt oppførsel hvertfall.

**Comment by sindrebroch** [comment]
Skal være løst i [release v2.1.0](https://github.com/sindrebroch/ha-flexit/releases/tag/v2.1.0). Har lagt på hastighet på vifter og varmegjenvinner, samt lagt på ny attributt på dirty_filter som viser gjenværende timer til filteret må byttes.

Det er en del kode som er omskrevet, så det er bare å melde inn hvis noe ikke funker som det skal :)

**Comment by kazzkizz** [comment]
Takker! Fungerer fint på Nordic CL4 :-)

**Comment by kazzkizz** [comment]
Hei - igjen! 
Kunne du også lagt til en siste sensor, det blir varmebatteriet? 
Takk! :)

**Comment by sindrebroch** [comment]
Det kan vi helt sikkert få på plass! Skal legge til neste gang jeg setter meg ned med det!

Til neste gang kan du gjerne åpne et nytt issue for nye ting, så blir det litt ryddigere :)

**Comment by sindrebroch** [comment]
Lagt til i [v2.1.1](https://github.com/sindrebroch/ha-flexit/releases/tag/v2.1.1). Litt usikker på hva den sensoren er hvis jeg skal være ærlig, og får bare 0 i verdi der selv, men mulig det bare er mitt anlegg :) Gjerne prøv og se om det funker, og evt åpne saken igjen hvis noe mangler

**Comment by kazzkizz** [comment]
Det er et varmebatteri i aggregatet som kan hjelpe med ca 1500w mener jeg for å øke temperatur litt. :) 
Viser 0% i øyeblikket, det samme gjør varmeveksler, som er helt korrekt. Skal gi en lyd om det ikke fungerer! Takk!

**Comment by sindrebroch** [comment]
Skjønner! Takk for tilbakemeldinger :)
