### ISSUE TITLE
«Wrong» icon for «Heating Electric Battery»

### ISSUE THREAD

**Issue by uphillbattle** [sindrebroch/ha-flexit#8]
Good job including a sensor for the «Heating Electric Battery» in release 2.1.1! 👍 I was missing that!

However, the «Heating Electric Battery» is actually just a «heater» although the Norwegian term used is «elbatteri». As someone explained in another issue, its a heating element that heats the supply air if the air temperature after the heat exchanger is too low.

Might I suggest that the icon (which today is the mdi:battery icon) is replaced by a heater icon, for example mdi:radiator? And perhaps change the sensor name to sensor.heater?

**Comment by sindrebroch** [comment]
Great input, updated in [2.1.2](https://github.com/sindrebroch/ha-flexit/releases/tag/v2.1.2). 

Changed the icon, and renamed to "Additional Heater". I prefer to remain somewhat consistant with the Flexit Go-app, and this is more precise than Electric Battery.
