### ISSUE TITLE
Legge til Ventilasjonsmodus

### ISSUE THREAD

**Issue by kazzkizz** [sindrebroch/ha-flexit#9]
Hei igjen! Fungerer strålende denne integrasjonen. 
På nordic cl4 har man 5 ventilasjonsmoduser; Home, Away, High, Fireplace, Kalender
Fikk plutselig bruk for fireplace her en kald morgen, og tenkte det kunne være fint med de andre modusene også :-) 
Edit; additional heater vises med 7 desimaler, dette kan jeg sikkert ordne i kortet som viser infoen?

**Comment by AndyveX** [comment]
Super bra jobb med denne. Om det er mulig å få inn modus hadde det vært strålende. Men det holder jo egentlig å bare stille tilluft og avtrekksviftehastigher (Extract Fan Control Signal og Supply Fan Control Signal) fra 0 til 100%
Kunne ikke se at det var muligen å stille hastighet på disse via integrasjonen. Om det er mulig å få inn så kan man jo lag modusene selv.

**Comment by AndyveX** [comment]
Ok. Får jeg satt home og away modus er mye gjort for min del 😀 Til info så fikk jeg forresten tips fra Flexit om å benytte denne appen https://apps.apple.com/no/app/abt-go/id1293043551?l=nb for å kunne sette fast IP fordi mitt aggregat da jeg mister forbindelse hele tide.

**Comment by uphillbattle** [comment]
> Ok. Får jeg satt home og away modus er mye gjort for min del 😀 Til info så fikk jeg forresten tips fra Flexit om å benytte denne appen https://apps.apple.com/no/app/abt-go/id1293043551?l=nb for å kunne sette fast IP fordi mitt aggregat da jeg mister forbindelse hele tide.

Interessant app (ABT Go). Lurer på om den kommuniserer med aggregatet lokalt (via (W)LAN) eller om den kommuniserer med Climatix-APIet. Dersom det første: Finnes det muliget for lokal kommunikasjon istedenfor via APIet også for Flexit-integrasjonen, mon tro?

Forresten har jeg sørget for at enheten har fast IP ved å reservere adressen ("static lease") i ruteren istedenfor å sette IP-adressen fast i aggregatet. Jeg synes den metoden gir meg bedre oversikt (kan se alle "static leases") ett sted (på ruteren).

**Comment by sindrebroch** [comment]
Støtte for Fireplace og Calendar er støttet nå i [2.2.0](https://github.com/sindrebroch/ha-flexit/releases/tag/2.2.0).
